CREATE DATABASE leaderboard_test;
USE leaderboard_test;
CREATE TABLE players (nick VARCHAR(20));
ALTER TABLE players ADD COLUMN (game VARCHAR(20), score SMALLINT);

ALTER TABLE players
  MODIFY COLUMN score SMALLINT UNSIGNED NOT NULL,
  MODIFY COLUMN game VARCHAR(20) NOT NULL,
  MODIFY COLUMN nick VARCHAR(20) NOT NULL;

ALTER TABLE players
  ADD COLUMN country VARCHAR(48) NOT NULL,
  ADD COLUMN city VARCHAR(85) NOT NULL;

ALTER TABLE players
  ADD COLUMN email VARCHAR(500);