CREATE DATABASE leaderboard;
USE leaderboard;
CREATE TABLE players (nick VARCHAR(20));
ALTER TABLE players ADD COLUMN (game VARCHAR(20), score SMALLINT);

ALTER TABLE players
  MODIFY COLUMN score SMALLINT UNSIGNED NOT NULL,
  MODIFY COLUMN game VARCHAR(20) NOT NULL,
  MODIFY COLUMN nick VARCHAR(20) NOT NULL;

ALTER TABLE players
  ADD COLUMN country VARCHAR(48) NOT NULL,
  ADD COLUMN city VARCHAR(85) NOT NULL;

ALTER TABLE players
  ADD COLUMN email VARCHAR(500);

DROP TABLE players;

CREATE TABLE players (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  nick VARCHAR(20) NOT NULL UNIQUE,
  email VARCHAR(500) UNIQUE
);

CREATE TABLE rounds (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  game VARCHAR(20) NOT NULL,
  score SMALLINT UNSIGNED NOT NULL,
  location_id INT UNSIGNED NOT NULL,
  player_id INT UNSIGNED NOT NULL,
  time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE locations (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  country VARCHAR(48) NOT NULL,
  city VARCHAR(85) NOT NULL
);

ALTER TABLE locations ADD UNIQUE INDEX(country, city);

ALTER TABLE rounds
  ADD FOREIGN KEY
  (player_id)
REFERENCES players (id)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE rounds
  ADD FOREIGN KEY
  (location_id)
REFERENCES locations (id)
  ON DELETE RESTRICT
  ON UPDATE CASCADE;

ALTER TABLE players ADD COLUMN password VARCHAR(255);