CREATE DATABASE leaderboard;
USE leaderboard;
CREATE TABLE players (nick VARCHAR(20));
ALTER TABLE players ADD COLUMN (game VARCHAR(20), score SMALLINT);
ALTER TABLE players
  MODIFY COLUMN score SMALLINT UNSIGNED NOT NULL,
  MODIFY COLUMN game VARCHAR(20) NOT NULL,
  MODIFY COLUMN nick VARCHAR(20) NOT NULL;