<?php

class PlayerTest extends PHPUnit\Framework\TestCase {

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        exec("cat ../../migrate_test.sql | mysql -h localhost -u root -pmob");
    }

    /**
     * @test
     */
    public function it_can_create_player() {

    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        exec("echo \"DROP DATABASE leaderboard_test;\" | mysql -h localhost -u root -pmob");
    }
}